/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: TGRRRR (https://sketchfab.com/Tgrrrr)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/fog-for-your-sketchfab-scenes-6d12cb257c964f268e418381125ecf0d
title: Fog for your SketchFab scenes
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    fog1__0: THREE.Mesh
    fog__0: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/aurora-transformed.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 619.33, -1542.65]} scale={[1027.98, 759.8, 631.23]}>
            <mesh geometry={nodes.fog1__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[1828.15, 619.33, 333.64]} rotation={[0, -Math.PI / 2, 0]} scale={[1027.98, 759.8, 631.23]}>
            <mesh geometry={nodes.fog__0.geometry} material={materials['Scene_-_Root']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/aurora-transformed.glb')
