/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: plaggy (https://sketchfab.com/plaggy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cc0-arrow-5-f38febed165240b9aea5289c215c6b65
title: CC0 - Arrow 5
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Arrow5_Arrow5_0: THREE.Mesh
  }
  materials: {
    Arrow5: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/cursor-transformed.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Sketchfab_model' }}>
        <group rotation={[Math.PI / 2, 0, 0]} userData={{ name: '1095acfb6b0747db8a7aadff5b388720.fbx' }}>
          <group userData={{ name: 'RootNode' }}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.03} userData={{ name: 'Arrow5' }}>
              <mesh geometry={nodes.Arrow5_Arrow5_0.geometry} material={materials.Arrow5} userData={{ name: 'Arrow5_Arrow5_0' }} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cursor-transformed.glb')
