/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Noob Model :D (https://sketchfab.com/koontanch)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/magic-ring-yellow-757ff3fbfb2045c68165c06494917faa
title: Magic Ring - Yellow
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane_0: THREE.Mesh
    Plane006_0: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Take 01'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/golden-portal-transformed.glb') as GLTFResult
  // @ts-ignore
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Plane" scale={2.99}>
              <mesh name="Plane_0" geometry={nodes.Plane_0.geometry} material={materials['Material.001']} />
            </group>
            <group name="Plane006" position={[0, 0, 0.04]} scale={2.99}>
              <mesh name="Plane006_0" geometry={nodes.Plane006_0.geometry} material={materials['Material.001']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/golden-portal-transformed.glb')
