/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Daniele Cocchi (https://sketchfab.com/Cocchi)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/80s-hacker-boy-room-low-poly-50519527cfa04f5db1e765a52567b527
title: 80s Hacker Boy Room - Low Poly
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pCube1_lambert2_0: THREE.Mesh
    pCube1_lambert3_0: THREE.Mesh
    pCube2_lambert9_0: THREE.Mesh
    pCube3_lambert9_0: THREE.Mesh
    pCube4_lambert9_0: THREE.Mesh
    pCube6_lambert9_0: THREE.Mesh
    pCube7_lambert9_0: THREE.Mesh
    pCube8_lambert9_0: THREE.Mesh
    pCube9_lambert9_0: THREE.Mesh
    pCube10_lambert18_0: THREE.Mesh
    pCube10_lambert20_0: THREE.Mesh
    pCube10_lambert19_0: THREE.Mesh
    pCylinder1_lambert11_0: THREE.Mesh
    pCube11_lambert10_0: THREE.Mesh
    pCube11_blinn2_0: THREE.Mesh
    pCube11_lambert1_0: THREE.Mesh
    pCube11_blinn3_0: THREE.Mesh
    pCube11_lambert21_0: THREE.Mesh
    pCube11_lambert30_0: THREE.Mesh
    pCube11_blinn10_0: THREE.Mesh
    pCube12_lambert13_0: THREE.Mesh
    pCube12_lambert1_0: THREE.Mesh
    pCube13_lambert14_0: THREE.Mesh
    pCube13_lambert1_0: THREE.Mesh
    pCube14_lambert24_0: THREE.Mesh
    pCube14_lambert25_0: THREE.Mesh
    pCube15_lambert26_0: THREE.Mesh
    pCube15_lambert28_0: THREE.Mesh
    pCube16_lambert17_0: THREE.Mesh
    pCube16_lambert12_0: THREE.Mesh
    pCube17_lambert15_0: THREE.Mesh
    pCube17_lambert16_0: THREE.Mesh
    pCube18_lambert1_0: THREE.Mesh
    pCylinder2_blinn1_0: THREE.Mesh
    pCylinder3_blinn1_0: THREE.Mesh
    pCube19_lambert4_0: THREE.Mesh
    pCube20_lambert8_0: THREE.Mesh
    pCube20_lambert7_0: THREE.Mesh
    pCube21_lambert5_0: THREE.Mesh
    pCube21_lambert6_0: THREE.Mesh
    pCube22_lambert22_0: THREE.Mesh
    pCube23_lambert23_0: THREE.Mesh
    pCylinder4_blinn5_0: THREE.Mesh
    pCylinder5_blinn4_0: THREE.Mesh
    pCube24_lambert1_0: THREE.Mesh
    pCylinder6_blinn4_0: THREE.Mesh
    pCube25_lambert15_0: THREE.Mesh
    pCube25_lambert16_0: THREE.Mesh
    pCube26_lambert29_0: THREE.Mesh
    clank_0016pCube41_clank_0016blinn3_0: THREE.Mesh
    clank_0016pCube41_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCube35_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube42_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube43_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube44_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCylinder7_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCube50_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube49_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube48_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube47_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCylinder9_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCylinder8_clank_0016blinn1_0: THREE.Mesh
    clank_0016pSphere3_clank_0016blinn1_0: THREE.Mesh
    clank_0016pSphere3_clank_0016phong4_0: THREE.Mesh
    clank_0016pCylinder12_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCylinder4_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCylinder3_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCylinder10_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCylinder11_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCube2_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCube25_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube28_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCylinder15_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCylinder14_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCylinder1_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCylinder6_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCube54_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube53_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube52_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube51_clank_0016blinn2_0: THREE.Mesh
    clank_0016pSphere2_clank_0016blinn1_0: THREE.Mesh
    clank_0016pSphere2_clank_0016phong3_0: THREE.Mesh
    clank_0016pSphere2_clank_0016phong2_0: THREE.Mesh
    clank_0016pCylinder13_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCylinder18_clank_0016blinn2_0: THREE.Mesh
    clank_0016pSphere8_clank_0016blinn1_0: THREE.Mesh
    clank_0016pSphere8_clank_0016blinn6_0: THREE.Mesh
    clank_0016pCylinder17_clank_0016blinn2_0: THREE.Mesh
    clank_0016pSphere5_clank_0016blinn1_0: THREE.Mesh
    clank_0016pSphere6_clank_0016phong1_0: THREE.Mesh
    clank_0016pSphere6_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCylinder19_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCylinder24_clank_0016blinn1_0: THREE.Mesh
    clank_0016pSphere4_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCube36_clank_0016blinn2_0: THREE.Mesh
    clank_0016pSphere10_clank_0016phongE1_0: THREE.Mesh
    clank_0016pSphere9_clank_0016phongE1_0: THREE.Mesh
    clank_0016pCube3_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCylinder25_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube10_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube30_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube31_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube32_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube1_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCube1_clank_0016blinn4_0: THREE.Mesh
    clank_0016pCube29_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube33_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube37_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube38_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube34_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube39_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube40_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube27_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCylinder21_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube22_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube45_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube8_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube4_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube46_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube7_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube9_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube6_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube5_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube15_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube14_clank_0016blinn5_0: THREE.Mesh
    clank_0016pCube13_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube11_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube12_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube17_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube24_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube16_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCube26_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCylinder16_clank_0016blinn2_0: THREE.Mesh
    clank_0016pCylinder5_clank_0016blinn1_0: THREE.Mesh
    clank_0016pCylinder2_clank_0016blinn1_0: THREE.Mesh
    pCylinder7_lambert31_0: THREE.Mesh
    pCube27_lambert34_0: THREE.Mesh
    pSphere1_lambert31_0: THREE.Mesh
    pCylinder8_lambert32_0: THREE.Mesh
    pCylinder10_lambert35_0: THREE.Mesh
    pCylinder9_lambert33_0: THREE.Mesh
    pCylinder7_lambert31_0_1: THREE.Mesh
    pCube27_lambert34_0_1: THREE.Mesh
    pSphere1_lambert31_0_1: THREE.Mesh
    pCylinder8_lambert32_0_1: THREE.Mesh
    pCylinder10_lambert35_0_1: THREE.Mesh
    pCylinder9_lambert33_0_1: THREE.Mesh
    pCube28_blinn8_0: THREE.Mesh
    pCube29_blinn8_0: THREE.Mesh
    pCube30_blinn6_0: THREE.Mesh
    pCube31_blinn7_0: THREE.Mesh
    pCube32_blinn6_0: THREE.Mesh
    pCube33_blinn7_0: THREE.Mesh
    pCube34_blinn7_0: THREE.Mesh
    pCube35_blinn6_0: THREE.Mesh
    pCube36_blinn6_0: THREE.Mesh
    pCube37_blinn6_0: THREE.Mesh
    pCylinder11_blinn9_0: THREE.Mesh
    pCylinder12_blinn9_0: THREE.Mesh
    pCube38_lambert36_0: THREE.Mesh
    NMSMultyTool_0010pCube2_NMSMultyTool_0010phong4_0: THREE.Mesh
    NMSMultyTool_0010pCube2_NMSMultyTool_0010phong1_0: THREE.Mesh
    NMSMultyTool_0010pCylinder2_NMSMultyTool_0010phong7_0: THREE.Mesh
    NMSMultyTool_0010pCylinder2_NMSMultyTool_0010phong8_0: THREE.Mesh
    NMSMultyTool_0010pCylinder2_NMSMultyTool_0010phong2_0: THREE.Mesh
    NMSMultyTool_0010pSphere1_NMSMultyTool_0010phong2_0: THREE.Mesh
    NMSMultyTool_0010pSphere1_NMSMultyTool_0010phong5_0: THREE.Mesh
    NMSMultyTool_0010pSphere1_NMSMultyTool_0010phong6_0: THREE.Mesh
    NMSMultyTool_0010pCylinder1_NMSMultyTool_0010phong2_0: THREE.Mesh
    NMSMultyTool_0010pCube1_NMSMultyTool_0010phong1_0: THREE.Mesh
    NMSMultyTool_0010pCube1_NMSMultyTool_0010phong3_0: THREE.Mesh
    NMSMultyTool_0010pCube3_NMSMultyTool_0010phong2_0: THREE.Mesh
    NMSMultyTool_0010pCylinder5_NMSMultyTool_0010phong1_0: THREE.Mesh
    NMSMultyTool_0010pSphere3_NMSMultyTool_0010phong1_0: THREE.Mesh
    NMSMultyTool_0010pCylinder8_NMSMultyTool_0010phong7_0: THREE.Mesh
    NMSMultyTool_0010pCylinder8_NMSMultyTool_0010phong8_0: THREE.Mesh
    NMSMultyTool_0010pCylinder8_NMSMultyTool_0010phong2_0: THREE.Mesh
    NMSMultyTool_0010pCylinder7_NMSMultyTool_0010phong7_0: THREE.Mesh
    NMSMultyTool_0010pCylinder7_NMSMultyTool_0010phong8_0: THREE.Mesh
    NMSMultyTool_0010pCylinder7_NMSMultyTool_0010phong2_0: THREE.Mesh
    NMSMultyTool_0010pSphere2_NMSMultyTool_0010phong2_0: THREE.Mesh
    NMSMultyTool_0010pCylinder3_NMSMultyTool_0010phong9_0: THREE.Mesh
    NMSMultyTool_0010pCylinder3_NMSMultyTool_0010phong1_0: THREE.Mesh
    NMSMultyTool_0010pCylinder4_NMSMultyTool_0010phong10_0: THREE.Mesh
    NMSMultyTool_0010pCylinder4_NMSMultyTool_0010phong1_0: THREE.Mesh
  }
  materials: {
    lambert2: THREE.MeshStandardMaterial
    lambert3: THREE.MeshStandardMaterial
    lambert9: THREE.MeshStandardMaterial
    lambert18: THREE.MeshStandardMaterial
    lambert20: THREE.MeshStandardMaterial
    lambert19: THREE.MeshStandardMaterial
    lambert11: THREE.MeshStandardMaterial
    lambert10: THREE.MeshStandardMaterial
    blinn2: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    blinn3: THREE.MeshStandardMaterial
    lambert21: THREE.MeshStandardMaterial
    lambert30: THREE.MeshStandardMaterial
    blinn10: THREE.MeshStandardMaterial
    lambert13: THREE.MeshStandardMaterial
    lambert14: THREE.MeshStandardMaterial
    lambert24: THREE.MeshStandardMaterial
    lambert25: THREE.MeshStandardMaterial
    lambert28: THREE.MeshStandardMaterial
    lambert17: THREE.MeshStandardMaterial
    lambert12: THREE.MeshStandardMaterial
    lambert15: THREE.MeshStandardMaterial
    lambert16: THREE.MeshStandardMaterial
    blinn1: THREE.MeshStandardMaterial
    lambert4: THREE.MeshStandardMaterial
    lambert8: THREE.MeshStandardMaterial
    lambert7: THREE.MeshStandardMaterial
    lambert6: THREE.MeshStandardMaterial
    blinn5: THREE.MeshStandardMaterial
    blinn4: THREE.MeshStandardMaterial
    clank_0016blinn3: THREE.MeshStandardMaterial
    clank_0016blinn1: THREE.MeshStandardMaterial
    clank_0016blinn2: THREE.MeshStandardMaterial
    clank_0016phong4: THREE.MeshStandardMaterial
    clank_0016phong3: THREE.MeshStandardMaterial
    clank_0016phong2: THREE.MeshStandardMaterial
    clank_0016blinn6: THREE.MeshStandardMaterial
    clank_0016phong1: THREE.MeshStandardMaterial
    clank_0016phongE1: THREE.MeshStandardMaterial
    clank_0016blinn4: THREE.MeshStandardMaterial
    lambert31: THREE.MeshStandardMaterial
    lambert35: THREE.MeshStandardMaterial
    blinn8: THREE.MeshStandardMaterial
    lambert36: THREE.MeshStandardMaterial
    NMSMultyTool_0010phong4: THREE.MeshStandardMaterial
    NMSMultyTool_0010phong1: THREE.MeshStandardMaterial
    NMSMultyTool_0010phong7: THREE.MeshStandardMaterial
    NMSMultyTool_0010phong8: THREE.MeshStandardMaterial
    NMSMultyTool_0010phong2: THREE.MeshStandardMaterial
    NMSMultyTool_0010phong5: THREE.MeshStandardMaterial
    NMSMultyTool_0010phong6: THREE.MeshStandardMaterial
    NMSMultyTool_0010phong3: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/hacker80-transformed.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-33.9, -6.9, -20.3]} rotation={[-1.33, 0, -0.82]} userData={{ name: 'Sketchfab_model' }}>
        <group rotation={[Math.PI / 2, 0, 0]} userData={{ name: '8994066be0de4a768c25de327100a1a7.fbx' }}>
          <group userData={{ name: 'RootNode' }}>
            <group position={[0, 0.15, -46.87]} rotation={[0, -Math.PI / 2, 0]} scale={[38, 1.5, 38]} userData={{ name: 'pCube1' }}>
              <mesh geometry={nodes.pCube1_lambert2_0.geometry} material={materials.lambert2} userData={{ name: 'pCube1_lambert2_0' }} />
              <mesh geometry={nodes.pCube1_lambert3_0.geometry} material={materials.lambert3} userData={{ name: 'pCube1_lambert3_0' }} />
            </group>
            <group position={[-12.18, 9, -52.88]} scale={[8, 0.74, 19.94]} userData={{ name: 'pCube2' }}>
              <mesh geometry={nodes.pCube2_lambert9_0.geometry} material={materials.lambert9} userData={{ name: 'pCube2_lambert9_0' }} />
            </group>
            <group position={[-9.45, 5.07, -44.87]} scale={[1.22, 8.09, 1.22]} userData={{ name: 'pCube3' }}>
              <mesh geometry={nodes.pCube3_lambert9_0.geometry} material={materials.lambert9} userData={{ name: 'pCube3_lambert9_0' }} />
            </group>
            <group position={[-15.08, 5.07, -44.87]} scale={[1.22, 8.09, 1.22]} userData={{ name: 'pCube4' }}>
              <mesh geometry={nodes.pCube4_lambert9_0.geometry} material={materials.lambert9} userData={{ name: 'pCube4_lambert9_0' }} />
            </group>
            <group position={[10.55, 5.07, -56.73]} scale={[1.22, 8.09, 1.22]} userData={{ name: 'pCube6' }}>
              <mesh geometry={nodes.pCube6_lambert9_0.geometry} material={materials.lambert9} userData={{ name: 'pCube6_lambert9_0' }} />
            </group>
            <group position={[-5.45, 5.07, -56.73]} scale={[1.22, 8.09, 1.22]} userData={{ name: 'pCube7' }}>
              <mesh geometry={nodes.pCube7_lambert9_0.geometry} material={materials.lambert9} userData={{ name: 'pCube7_lambert9_0' }} />
            </group>
            <group position={[10.55, 5.07, -61.64]} scale={[1.22, 8.09, 1.22]} userData={{ name: 'pCube8' }}>
              <mesh geometry={nodes.pCube8_lambert9_0.geometry} material={materials.lambert9} userData={{ name: 'pCube8_lambert9_0' }} />
            </group>
            <group position={[-5.45, 5.07, -61.64]} scale={[1.22, 8.09, 1.22]} userData={{ name: 'pCube9' }}>
              <mesh geometry={nodes.pCube9_lambert9_0.geometry} material={materials.lambert9} userData={{ name: 'pCube9_lambert9_0' }} />
            </group>
            <group position={[-12.48, 11.74, -47.77]} rotation={[0, 0.3, 0]} scale={[3.51, 3.51, 4.01]} userData={{ name: 'pCube10' }}>
              <mesh geometry={nodes.pCube10_lambert18_0.geometry} material={materials.lambert18} userData={{ name: 'pCube10_lambert18_0' }} />
              <mesh geometry={nodes.pCube10_lambert20_0.geometry} material={materials.lambert20} userData={{ name: 'pCube10_lambert20_0' }} />
              <mesh geometry={nodes.pCube10_lambert19_0.geometry} material={materials.lambert19} userData={{ name: 'pCube10_lambert19_0' }} />
            </group>
            <group position={[-11, 3.52, -48.08]} scale={2.63} userData={{ name: 'pCylinder1' }}>
              <mesh geometry={nodes.pCylinder1_lambert11_0.geometry} material={materials.lambert11} userData={{ name: 'pCylinder1_lambert11_0' }} />
            </group>
            <group position={[-14.01, 10.63, -41.87]} scale={[10.98, 19.56, 0.72]} userData={{ name: 'pCube11' }}>
              <mesh geometry={nodes.pCube11_lambert10_0.geometry} material={materials.lambert10} userData={{ name: 'pCube11_lambert10_0' }} />
              <mesh geometry={nodes.pCube11_blinn2_0.geometry} material={materials.blinn2} userData={{ name: 'pCube11_blinn2_0' }} />
              <mesh geometry={nodes.pCube11_lambert1_0.geometry} material={materials.lambert1} userData={{ name: 'pCube11_lambert1_0' }} />
              <mesh geometry={nodes.pCube11_blinn3_0.geometry} material={materials.blinn3} userData={{ name: 'pCube11_blinn3_0' }} />
              <mesh geometry={nodes.pCube11_lambert21_0.geometry} material={materials.lambert21} userData={{ name: 'pCube11_lambert21_0' }} />
              <mesh geometry={nodes.pCube11_lambert30_0.geometry} material={materials.lambert30} userData={{ name: 'pCube11_lambert30_0' }} />
              <mesh geometry={nodes.pCube11_blinn10_0.geometry} material={materials.blinn10} userData={{ name: 'pCube11_blinn10_0' }} />
            </group>
            <group position={[-3.13, 9.98, -60.58]} scale={[6.02, 1.27, 4.19]} userData={{ name: 'pCube12' }}>
              <mesh geometry={nodes.pCube12_lambert13_0.geometry} material={materials.lambert13} userData={{ name: 'pCube12_lambert13_0' }} />
              <mesh geometry={nodes.pCube12_lambert1_0.geometry} material={materials.lambert1} userData={{ name: 'pCube12_lambert1_0' }} />
            </group>
            <group position={[-12.18, 10.16, -59.11]} rotation={[0, Math.PI / 4, 0]} scale={[7.07, 1.6, 5.75]} userData={{ name: 'pCube13' }}>
              <mesh geometry={nodes.pCube13_lambert14_0.geometry} material={materials.lambert14} userData={{ name: 'pCube13_lambert14_0' }} />
              <mesh geometry={nodes.pCube13_lambert1_0.geometry} material={materials.lambert1} userData={{ name: 'pCube13_lambert1_0' }} />
            </group>
            <group position={[-13.44, 14.51, -60.22]} rotation={[0, -Math.PI / 4, 0]} scale={[6.99, 5.38, 6.4]} userData={{ name: 'pCube14' }}>
              <mesh geometry={nodes.pCube14_lambert24_0.geometry} material={materials.lambert24} userData={{ name: 'pCube14_lambert24_0' }} />
              <mesh geometry={nodes.pCube14_lambert25_0.geometry} material={materials.lambert25} userData={{ name: 'pCube14_lambert25_0' }} />
            </group>
            <group position={[-3.18, 13.41, -61.47]} rotation={[0, -Math.PI / 2, 0]} scale={[5.24, 4.26, 4.72]} userData={{ name: 'pCube15' }}>
              <mesh geometry={nodes.pCube15_lambert26_0.geometry} material={materials.lambert24} userData={{ name: 'pCube15_lambert26_0' }} />
              <mesh geometry={nodes.pCube15_lambert28_0.geometry} material={materials.lambert28} userData={{ name: 'pCube15_lambert28_0' }} />
            </group>
            <group position={[4.4, 11.17, -59.66]} rotation={[0, -Math.PI / 6, 0]} scale={[6.24, 3.7, 3.82]} userData={{ name: 'pCube16' }}>
              <mesh geometry={nodes.pCube16_lambert17_0.geometry} material={materials.lambert17} userData={{ name: 'pCube16_lambert17_0' }} />
              <mesh geometry={nodes.pCube16_lambert12_0.geometry} material={materials.lambert12} userData={{ name: 'pCube16_lambert12_0' }} />
            </group>
            <group position={[-9.11, 9.53, -54.77]} rotation={[0, 0.54, 0]} scale={[7.53, 0.28, 2.36]} userData={{ name: 'pCube17' }}>
              <mesh geometry={nodes.pCube17_lambert15_0.geometry} material={materials.lambert15} userData={{ name: 'pCube17_lambert15_0' }} />
              <mesh geometry={nodes.pCube17_lambert16_0.geometry} material={materials.lambert16} userData={{ name: 'pCube17_lambert16_0' }} />
            </group>
            <group position={[-4.14, 9.51, -56.05]} rotation={[-Math.PI, -1.31, -Math.PI]} scale={[1.33, 0.27, 0.8]} userData={{ name: 'pCube18' }}>
              <mesh geometry={nodes.pCube18_lambert1_0.geometry} material={materials.lambert1} userData={{ name: 'pCube18_lambert1_0' }} />
            </group>
            <group position={[-15.55, 23.94, -46.51]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.36, 17.59, 1.36]} userData={{ name: 'pCylinder2' }}>
              <mesh geometry={nodes.pCylinder2_blinn1_0.geometry} material={materials.blinn1} userData={{ name: 'pCylinder2_blinn1_0' }} />
            </group>
            <group position={[-15.55, 11.97, -62.31]} rotation={[-Math.PI, 0, 0]} scale={[1.36, 11.86, 1.36]} userData={{ name: 'pCylinder3' }}>
              <mesh geometry={nodes.pCylinder3_blinn1_0.geometry} material={materials.blinn1} userData={{ name: 'pCylinder3_blinn1_0' }} />
            </group>
            <group position={[8.38, 4.55, -35]} rotation={[-Math.PI, -0.14, -Math.PI]} scale={[21.46, 9.63, 8.85]} userData={{ name: 'pCube19' }}>
              <mesh geometry={nodes.pCube19_lambert4_0.geometry} material={materials.lambert4} userData={{ name: 'pCube19_lambert4_0' }} />
            </group>
            <group position={[-0.9, 18.58, -63.77]} scale={[10.28, 13.95, 0.25]} userData={{ name: 'pCube20' }}>
              <mesh geometry={nodes.pCube20_lambert8_0.geometry} material={materials.lambert8} userData={{ name: 'pCube20_lambert8_0' }} />
              <mesh geometry={nodes.pCube20_lambert7_0.geometry} material={materials.lambert7} userData={{ name: 'pCube20_lambert7_0' }} />
            </group>
            <group position={[12.01, 18.77, -63.77]} rotation={[0, 0, 0.04]} scale={[7.52, 11.16, 0.21]} userData={{ name: 'pCube21' }}>
              <mesh geometry={nodes.pCube21_lambert5_0.geometry} material={materials.lambert7} userData={{ name: 'pCube21_lambert5_0' }} />
              <mesh geometry={nodes.pCube21_lambert6_0.geometry} material={materials.lambert6} userData={{ name: 'pCube21_lambert6_0' }} />
            </group>
            <group position={[-16.84, 19.35, -45.11]} rotation={[-Math.PI / 2, 1.53, 1.67]} scale={[2.61, 3.87, 0.07]} userData={{ name: 'pCube22' }}>
              <mesh geometry={nodes.pCube22_lambert22_0.geometry} material={materials.lambert9} userData={{ name: 'pCube22_lambert22_0' }} />
            </group>
            <group position={[-16.84, 18.31, -46.93]} rotation={[-Math.PI / 2, 1.53, 1.39]} scale={[2.61, 3.87, 0.07]} userData={{ name: 'pCube23' }}>
              <mesh geometry={nodes.pCube23_lambert23_0.geometry} material={materials.lambert9} userData={{ name: 'pCube23_lambert23_0' }} />
            </group>
            <group position={[0.45, 9.4, -56.62]} rotation={[0, -0.08, 0]} scale={[0.9, 0.03, 0.9]} userData={{ name: 'pCylinder4' }}>
              <mesh geometry={nodes.pCylinder4_blinn5_0.geometry} material={materials.blinn5} userData={{ name: 'pCylinder4_blinn5_0' }} />
            </group>
            <group position={[-13.96, 13.94, -52.18]} rotation={[0.06, -0.01, 0.23]} scale={[1, 1.41, 1]} userData={{ name: 'pCylinder5' }}>
              <mesh geometry={nodes.pCylinder5_blinn4_0.geometry} material={materials.blinn4} userData={{ name: 'pCylinder5_blinn4_0' }} />
            </group>
            <group position={[-16.56, 14.06, -52.16]} rotation={[0, 0, -1.19]} scale={[0.32, 4.34, 0.32]} userData={{ name: 'pCube24' }}>
              <mesh geometry={nodes.pCube24_lambert1_0.geometry} material={materials.lambert1} userData={{ name: 'pCube24_lambert1_0' }} />
            </group>
            <group position={[-14.87, 9.51, -52.14]} rotation={[Math.PI, 0.08, 0]} scale={[0.9, 0.03, 0.9]} userData={{ name: 'pCylinder6' }}>
              <mesh geometry={nodes.pCylinder6_blinn4_0.geometry} material={materials.blinn4} userData={{ name: 'pCylinder6_blinn4_0' }} />
            </group>
            <group position={[9.22, 13.06, -62.55]} rotation={[-Math.PI, 1.56, -1.83]} scale={[7.53, 0.28, 2.36]} userData={{ name: 'pCube25' }}>
              <mesh geometry={nodes.pCube25_lambert15_0.geometry} material={materials.lambert15} userData={{ name: 'pCube25_lambert15_0' }} />
              <mesh geometry={nodes.pCube25_lambert16_0.geometry} material={materials.lambert16} userData={{ name: 'pCube25_lambert16_0' }} />
            </group>
            <group position={[-14.85, 18.3, -54.92]} scale={[4.47, 0.58, 11.13]} userData={{ name: 'pCube26' }}>
              <mesh geometry={nodes.pCube26_lambert29_0.geometry} material={materials.lambert9} userData={{ name: 'pCube26_lambert29_0' }} />
            </group>
            <group position={[-13.48, 21.15, -5.26]} rotation={[0, -0.59, 0]} scale={0.22} userData={{ name: 'group1' }}>
              <group position={[-130.22, -2.31, -192.96]} rotation={[0, 0, 0.08]} scale={[1, 3.26, 3.08]} userData={{ name: 'clank_0016:pCube41' }}>
                <mesh geometry={nodes.clank_0016pCube41_clank_0016blinn3_0.geometry} material={materials.clank_0016blinn3} userData={{ name: 'clank_0016:pCube41_clank_0016:blinn3_0' }} />
                <mesh geometry={nodes.clank_0016pCube41_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCube41_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-131.93, -7.49, -195.09]} rotation={[-Math.PI / 2, -Math.PI / 3, Math.PI / 2]} scale={[0.76, 0.76, 0.82]} userData={{ name: 'clank_0016:pCube35' }}>
                <mesh geometry={nodes.clank_0016pCube35_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube35_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-129.58, -1.55, -192.99]} rotation={[0, 0, 0.47]} scale={[0.07, 0.48, 2.04]} userData={{ name: 'clank_0016:pCube42' }}>
                <mesh geometry={nodes.clank_0016pCube42_clank_0016blinn2_0.geometry} material={materials.lambert9} userData={{ name: 'clank_0016:pCube42_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-129.52, -2.29, -192.99]} rotation={[0, 0, 0.47]} scale={[0.07, 0.48, 2.04]} userData={{ name: 'clank_0016:pCube43' }}>
                <mesh geometry={nodes.clank_0016pCube43_clank_0016blinn2_0.geometry} material={materials.lambert9} userData={{ name: 'clank_0016:pCube43_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-129.47, -3, -192.99]} rotation={[0, 0, 0.47]} scale={[0.07, 0.48, 2.04]} userData={{ name: 'clank_0016:pCube44' }}>
                <mesh geometry={nodes.clank_0016pCube44_clank_0016blinn2_0.geometry} material={materials.lambert9} userData={{ name: 'clank_0016:pCube44_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.93, -7.49, -194.69]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 0.58, 0.71]} userData={{ name: 'clank_0016:pCylinder7' }}>
                <mesh geometry={nodes.clank_0016pCylinder7_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder7_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-134.22, -1.04, -192.98]} rotation={[0, 0, -2.94]} scale={[0.06, 0.32, 1.29]} userData={{ name: 'clank_0016:pCube50' }}>
                <mesh geometry={nodes.clank_0016pCube50_clank_0016blinn2_0.geometry} material={materials.lambert9} userData={{ name: 'clank_0016:pCube50_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-134.24, -1.5, -192.98]} rotation={[0, 0, -2.94]} scale={[0.06, 0.32, 1.29]} userData={{ name: 'clank_0016:pCube49' }}>
                <mesh geometry={nodes.clank_0016pCube49_clank_0016blinn2_0.geometry} material={materials.lambert9} userData={{ name: 'clank_0016:pCube49_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-134.26, -1.96, -192.98]} rotation={[0, 0, -2.94]} scale={[0.06, 0.32, 1.29]} userData={{ name: 'clank_0016:pCube48' }}>
                <mesh geometry={nodes.clank_0016pCube48_clank_0016blinn2_0.geometry} material={materials.lambert9} userData={{ name: 'clank_0016:pCube48_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-133.62, -1.57, -192.97]} rotation={[0, 0, 3.05]} scale={[0.89, 2.06, 1.95]} userData={{ name: 'clank_0016:pCube47' }}>
                <mesh geometry={nodes.clank_0016pCube47_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube47_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.93, 1.09, -192.99]} scale={[0.44, 0.78, 0.44]} userData={{ name: 'clank_0016:pCylinder9' }}>
                <mesh geometry={nodes.clank_0016pCylinder9_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder9_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.93, -7.49, -191.27]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 0.58, 0.71]} userData={{ name: 'clank_0016:pCylinder8' }}>
                <mesh geometry={nodes.clank_0016pCylinder8_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder8_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-130.73, -11.44, -191.23]} rotation={[0, Math.PI / 2, 0]} scale={[1.33, 1.24, 2.54]} userData={{ name: 'clank_0016:pSphere3' }}>
                <mesh geometry={nodes.clank_0016pSphere3_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pSphere3_clank_0016:blinn1_0' }} />
                <mesh geometry={nodes.clank_0016pSphere3_clank_0016phong4_0.geometry} material={materials.clank_0016phong4} userData={{ name: 'clank_0016:pSphere3_clank_0016:phong4_0' }} />
              </group>
              <group position={[-131.93, -9.68, -194.53]} rotation={[Math.PI / 2, 0, 0]} scale={[0.58, 0.87, 0.58]} userData={{ name: 'clank_0016:pCylinder12' }}>
                <mesh geometry={nodes.clank_0016pCylinder12_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder12_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-131.93, -5.35, -192.98]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 2.25, 0.25]} userData={{ name: 'clank_0016:pCylinder4' }}>
                <mesh geometry={nodes.clank_0016pCylinder4_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder4_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-131.93, 0.75, -192.99]} scale={[0.77, 0.35, 0.77]} userData={{ name: 'clank_0016:pCylinder3' }}>
                <mesh geometry={nodes.clank_0016pCylinder3_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder3_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-131.93, -5.62, -191.24]} scale={[0.42, 0.65, 0.42]} userData={{ name: 'clank_0016:pCylinder10' }}>
                <mesh geometry={nodes.clank_0016pCylinder10_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder10_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-131.93, -9.68, -191.33]} rotation={[Math.PI / 2, 0, 0]} scale={[0.58, 0.87, 0.58]} userData={{ name: 'clank_0016:pCylinder11' }}>
                <mesh geometry={nodes.clank_0016pCylinder11_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder11_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-127.25, -3.45, -195.95]} rotation={[-Math.PI / 2, Math.PI / 6, 1.31]} scale={[1.04, 2.57, 2.66]} userData={{ name: 'clank_0016:pCube2' }}>
                <mesh geometry={nodes.clank_0016pCube2_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCube2_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-129.76, -2, -196.44]} rotation={[-Math.PI / 2, -0.26, Math.PI / 2]} scale={[0.58, 0.58, 0.63]} userData={{ name: 'clank_0016:pCube25' }}>
                <mesh geometry={nodes.clank_0016pCube25_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube25_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.94, -0.74, -196.21]} rotation={[Math.PI / 2, -Math.PI / 3, -Math.PI / 2]} scale={[1.1, 1.1, 1.19]} userData={{ name: 'clank_0016:pCube28' }}>
                <mesh geometry={nodes.clank_0016pCube28_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube28_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-129.52, -2.14, -196.03]} rotation={[0, 0, Math.PI / 3]} scale={[0.35, 2.93, 0.35]} userData={{ name: 'clank_0016:pCylinder15' }}>
                <mesh geometry={nodes.clank_0016pCylinder15_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCylinder15_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.9, -0.77, -192.98]} rotation={[Math.PI / 2, Math.PI / 3, 0]} scale={[0.31, 3.18, 0.31]} userData={{ name: 'clank_0016:pCylinder14' }}>
                <mesh geometry={nodes.clank_0016pCylinder14_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder14_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.93, -0.75, -196.01]} rotation={[-Math.PI / 2, -Math.PI / 3, 0]} scale={[1.1, 0.49, 1.1]} userData={{ name: 'clank_0016:pCylinder1' }}>
                <mesh geometry={nodes.clank_0016pCylinder1_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder1_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-129.75, -2.01, -196.04]} rotation={[Math.PI / 2, Math.PI / 3, 0]} scale={[0.59, 0.47, 0.59]} userData={{ name: 'clank_0016:pCylinder6' }}>
                <mesh geometry={nodes.clank_0016pCylinder6_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder6_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-131.33, -1.71, -194.73]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.38, 0.38, 0.41]} userData={{ name: 'clank_0016:pCube54' }}>
                <mesh geometry={nodes.clank_0016pCube54_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube54_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-132.59, -1.71, -194.73]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.38, 0.38, 0.41]} userData={{ name: 'clank_0016:pCube53' }}>
                <mesh geometry={nodes.clank_0016pCube53_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube53_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.33, -1.71, -191.17]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.38, 0.38, 0.41]} userData={{ name: 'clank_0016:pCube52' }}>
                <mesh geometry={nodes.clank_0016pCube52_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube52_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-132.59, -1.71, -191.17]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.38, 0.38, 0.41]} userData={{ name: 'clank_0016:pCube51' }}>
                <mesh geometry={nodes.clank_0016pCube51_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube51_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-130.73, -11.44, -194.61]} rotation={[0, Math.PI / 2, 0]} scale={[1.33, 1.24, 2.54]} userData={{ name: 'clank_0016:pSphere2' }}>
                <mesh geometry={nodes.clank_0016pSphere2_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pSphere2_clank_0016:blinn1_0' }} />
                <mesh geometry={nodes.clank_0016pSphere2_clank_0016phong3_0.geometry} material={materials.clank_0016phong3} userData={{ name: 'clank_0016:pSphere2_clank_0016:phong3_0' }} />
                <mesh geometry={nodes.clank_0016pSphere2_clank_0016phong2_0.geometry} material={materials.clank_0016phong2} userData={{ name: 'clank_0016:pSphere2_clank_0016:phong2_0' }} />
              </group>
              <group position={[-131.93, -5.62, -194.69]} scale={[0.42, 0.65, 0.42]} userData={{ name: 'clank_0016:pCylinder13' }}>
                <mesh geometry={nodes.clank_0016pCylinder13_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder13_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-131.93, -8.46, -194.67]} rotation={[-Math.PI, 0, 0]} scale={[0.35, 2.44, 0.35]} userData={{ name: 'clank_0016:pCylinder18' }}>
                <mesh geometry={nodes.clank_0016pCylinder18_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCylinder18_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.96, 4.47, -193.12]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[3.23, 2.62, 2.66]} userData={{ name: 'clank_0016:pSphere8' }}>
                <mesh geometry={nodes.clank_0016pSphere8_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pSphere8_clank_0016:blinn1_0' }} />
                <mesh geometry={nodes.clank_0016pSphere8_clank_0016blinn6_0.geometry} material={materials.clank_0016blinn6} userData={{ name: 'clank_0016:pSphere8_clank_0016:blinn6_0' }} />
              </group>
              <group position={[-131.93, -8.46, -191.24]} rotation={[-Math.PI, 0, 0]} scale={[0.35, 2.44, 0.35]} userData={{ name: 'clank_0016:pCylinder17' }}>
                <mesh geometry={nodes.clank_0016pCylinder17_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCylinder17_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.93, -0.76, -191.36]} scale={0.52} userData={{ name: 'clank_0016:pSphere5' }}>
                <mesh geometry={nodes.clank_0016pSphere5_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pSphere5_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-131.93, 9.46, -192.99]} scale={0.52} userData={{ name: 'clank_0016:pSphere6' }}>
                <mesh geometry={nodes.clank_0016pSphere6_clank_0016phong1_0.geometry} material={materials.clank_0016phong1} userData={{ name: 'clank_0016:pSphere6_clank_0016:phong1_0' }} />
                <mesh geometry={nodes.clank_0016pSphere6_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pSphere6_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-131.93, 7.09, -192.98]} scale={0.46} userData={{ name: 'clank_0016:pCylinder19' }}>
                <mesh geometry={nodes.clank_0016pCylinder19_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder19_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-131.34, 3.85, -192.99]} rotation={[Math.PI / 2, 0, 0]} scale={[0.82, 2.65, 0.82]} userData={{ name: 'clank_0016:pCylinder24' }}>
                <mesh geometry={nodes.clank_0016pCylinder24_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder24_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-131.93, -0.76, -194.57]} scale={0.52} userData={{ name: 'clank_0016:pSphere4' }}>
                <mesh geometry={nodes.clank_0016pSphere4_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pSphere4_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-131.93, -7.49, -194.26]} rotation={[Math.PI / 2, -Math.PI / 3, Math.PI / 2]} scale={[0.76, 0.76, 0.82]} userData={{ name: 'clank_0016:pCube36' }}>
                <mesh geometry={nodes.clank_0016pCube36_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube36_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-129.67, 5.2, -193.92]} rotation={[-2.25, 1.24, 2.24]} scale={[0.79, 0.79, 0.43]} userData={{ name: 'clank_0016:pSphere10' }}>
                <mesh geometry={nodes.clank_0016pSphere10_clank_0016phongE1_0.geometry} material={materials.clank_0016phongE1} userData={{ name: 'clank_0016:pSphere10_clank_0016:phongE1_0' }} />
              </group>
              <group position={[-129.73, 5.2, -191.89]} rotation={[-0.7, 1.18, 0.74]} scale={[0.79, 0.79, 0.43]} userData={{ name: 'clank_0016:pSphere9' }}>
                <mesh geometry={nodes.clank_0016pSphere9_clank_0016phongE1_0.geometry} material={materials.clank_0016phongE1} userData={{ name: 'clank_0016:pSphere9_clank_0016:phongE1_0' }} />
              </group>
              <group position={[-126.5, -0.65, -189.98]} rotation={[-Math.PI / 2, 0, 1.83]} scale={[1.04, 2.57, 2.66]} userData={{ name: 'clank_0016:pCube3' }}>
                <mesh geometry={nodes.clank_0016pCube3_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCube3_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-125.61, 1.37, -190.34]} rotation={[-1.72, 0.5, -1.27]} scale={[0.07, 0.27, 0.1]} userData={{ name: 'clank_0016:pCylinder25' }}>
                <mesh geometry={nodes.clank_0016pCylinder25_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder25_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-123.72, -1.27, -190.72]} rotation={[-Math.PI / 2, 0, 1.83]} scale={[0.53, 0.95, 0.96]} userData={{ name: 'clank_0016:pCube10' }}>
                <mesh geometry={nodes.clank_0016pCube10_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube10_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.93, -9.67, -193.83]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.74, 0.74, 0.79]} userData={{ name: 'clank_0016:pCube30' }}>
                <mesh geometry={nodes.clank_0016pCube30_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube30_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.93, -9.67, -190.62]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.74, 0.74, 0.79]} userData={{ name: 'clank_0016:pCube31' }}>
                <mesh geometry={nodes.clank_0016pCube31_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube31_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.93, -9.67, -192.04]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.74, 0.74, 0.79]} userData={{ name: 'clank_0016:pCube32' }}>
                <mesh geometry={nodes.clank_0016pCube32_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube32_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.93, -1.78, -192.96]} rotation={[0, Math.PI / 2, 0]} scale={5.13} userData={{ name: 'clank_0016:pCube1' }}>
                <mesh geometry={nodes.clank_0016pCube1_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCube1_clank_0016:blinn1_0' }} />
                <mesh geometry={nodes.clank_0016pCube1_clank_0016blinn4_0.geometry} material={materials.clank_0016blinn4} userData={{ name: 'clank_0016:pCube1_clank_0016:blinn4_0' }} />
              </group>
              <group position={[-131.93, -9.67, -195.25]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.74, 0.74, 0.79]} userData={{ name: 'clank_0016:pCube29' }}>
                <mesh geometry={nodes.clank_0016pCube29_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube29_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.32, 3.86, -195.49]} rotation={[-Math.PI / 2, Math.PI / 4, Math.PI / 2]} scale={[0.65, 0.65, 0.7]} userData={{ name: 'clank_0016:pCube33' }}>
                <mesh geometry={nodes.clank_0016pCube33_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube33_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.93, -7.49, -190.86]} rotation={[Math.PI / 2, -Math.PI / 3, Math.PI / 2]} scale={[0.76, 0.76, 0.82]} userData={{ name: 'clank_0016:pCube37' }}>
                <mesh geometry={nodes.clank_0016pCube37_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube37_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.93, -7.49, -191.69]} rotation={[-Math.PI / 2, -Math.PI / 3, Math.PI / 2]} scale={[0.76, 0.76, 0.82]} userData={{ name: 'clank_0016:pCube38' }}>
                <mesh geometry={nodes.clank_0016pCube38_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube38_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.32, 3.86, -190.47]} rotation={[Math.PI / 2, Math.PI / 4, Math.PI / 2]} scale={[0.65, 0.65, 0.7]} userData={{ name: 'clank_0016:pCube34' }}>
                <mesh geometry={nodes.clank_0016pCube34_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube34_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.93, -5.34, -195.19]} rotation={[-Math.PI / 2, Math.PI / 4, Math.PI / 2]} scale={[0.25, 0.25, 0.27]} userData={{ name: 'clank_0016:pCube39' }}>
                <mesh geometry={nodes.clank_0016pCube39_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube39_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.93, -5.34, -190.77]} rotation={[Math.PI / 2, Math.PI / 4, Math.PI / 2]} scale={[0.25, 0.25, 0.27]} userData={{ name: 'clank_0016:pCube40' }}>
                <mesh geometry={nodes.clank_0016pCube40_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube40_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-131.92, -0.65, -189.73]} rotation={[Math.PI / 2, Math.PI / 6, Math.PI / 2]} scale={[1.1, 1.1, 1.19]} userData={{ name: 'clank_0016:pCube27' }}>
                <mesh geometry={nodes.clank_0016pCube27_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube27_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-125.46, -2.13, -195.68]} rotation={[-1.32, 1.02, 1.13]} scale={[0.07, 0.27, 0.1]} userData={{ name: 'clank_0016:pCylinder21' }}>
                <mesh geometry={nodes.clank_0016pCylinder21_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder21_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-127.55, -3.28, -196.43]} rotation={[-2.06, -0.99, 1.15]} scale={[0.74, 0.74, 0.79]} userData={{ name: 'clank_0016:pCube22' }}>
                <mesh geometry={nodes.clank_0016pCube22_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube22_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-125.99, -2.47, -195.79]} rotation={[-1.32, 1.02, 1.13]} scale={[0.59, 0.83, 1.2]} userData={{ name: 'clank_0016:pCube45' }}>
                <mesh geometry={nodes.clank_0016pCube45_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube45_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-125.19, -3.91, -195.44]} rotation={[-Math.PI / 2, Math.PI / 6, 1.31]} scale={[0.42, 1.99, 0.46]} userData={{ name: 'clank_0016:pCube8' }}>
                <mesh geometry={nodes.clank_0016pCube8_clank_0016blinn2_0.geometry} material={materials.lambert9} userData={{ name: 'clank_0016:pCube8_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-125.38, -3.8, -195.5]} rotation={[Math.PI / 2, -Math.PI / 6, 1.83]} scale={[0.64, 0.91, 1]} userData={{ name: 'clank_0016:pCube4' }}>
                <mesh geometry={nodes.clank_0016pCube4_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube4_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-125.14, -1.95, -195.58]} rotation={[-1.03, 0.92, 0.89]} scale={[0.45, 0.62, 0.61]} userData={{ name: 'clank_0016:pCube46' }}>
                <mesh geometry={nodes.clank_0016pCube46_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube46_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-125.14, -5.38, -195.23]} rotation={[-Math.PI / 2, Math.PI / 6, 1.31]} scale={[0.53, 0.95, 0.96]} userData={{ name: 'clank_0016:pCube7' }}>
                <mesh geometry={nodes.clank_0016pCube7_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube7_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-125.82, -5, -195.44]} rotation={[-Math.PI / 2, Math.PI / 6, 1.31]} scale={[0.42, 1.99, 0.46]} userData={{ name: 'clank_0016:pCube9' }}>
                <mesh geometry={nodes.clank_0016pCube9_clank_0016blinn2_0.geometry} material={materials.lambert9} userData={{ name: 'clank_0016:pCube9_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-126.01, -4.89, -195.5]} rotation={[Math.PI / 2, -Math.PI / 6, 1.83]} scale={[0.64, 0.91, 1]} userData={{ name: 'clank_0016:pCube6' }}>
                <mesh geometry={nodes.clank_0016pCube6_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube6_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-124.51, -4.28, -195.23]} rotation={[-Math.PI / 2, Math.PI / 6, 1.31]} scale={[0.53, 0.95, 0.96]} userData={{ name: 'clank_0016:pCube5' }}>
                <mesh geometry={nodes.clank_0016pCube5_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube5_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-124.72, -0.02, -190.45]} rotation={[Math.PI / 2, 0, 1.31]} scale={[0.64, 0.91, 1]} userData={{ name: 'clank_0016:pCube15' }}>
                <mesh geometry={nodes.clank_0016pCube15_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube15_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-124.5, -1.28, -190.51]} rotation={[-Math.PI / 2, 0, 1.83]} scale={[0.42, 1.99, 0.46]} userData={{ name: 'clank_0016:pCube14' }}>
                <mesh geometry={nodes.clank_0016pCube14_clank_0016blinn5_0.geometry} material={materials.lambert9} userData={{ name: 'clank_0016:pCube14_clank_0016:blinn5_0' }} />
              </group>
              <group position={[-124.5, -0.02, -190.51]} rotation={[-Math.PI / 2, 0, 1.83]} scale={[0.42, 1.99, 0.46]} userData={{ name: 'clank_0016:pCube13' }}>
                <mesh geometry={nodes.clank_0016pCube13_clank_0016blinn2_0.geometry} material={materials.lambert9} userData={{ name: 'clank_0016:pCube13_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-124.72, -1.28, -190.45]} rotation={[Math.PI / 2, 0, 1.31]} scale={[0.64, 0.91, 1]} userData={{ name: 'clank_0016:pCube11' }}>
                <mesh geometry={nodes.clank_0016pCube11_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube11_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-123.72, 0, -190.72]} rotation={[-Math.PI / 2, 0, 1.83]} scale={[0.53, 0.95, 0.96]} userData={{ name: 'clank_0016:pCube12' }}>
                <mesh geometry={nodes.clank_0016pCube12_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube12_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-125.45, 1.7, -190.43]} rotation={[-1.92, 0.44, -1.18]} scale={[0.45, 0.62, 0.61]} userData={{ name: 'clank_0016:pCube17' }}>
                <mesh geometry={nodes.clank_0016pCube17_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube17_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-126.84, -0.65, -189.48]} rotation={[0, -1.31, 0]} scale={[0.74, 0.74, 0.79]} userData={{ name: 'clank_0016:pCube24' }}>
                <mesh geometry={nodes.clank_0016pCube24_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube24_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-125.93, 0.82, -190.22]} rotation={[-1.72, 0.5, -1.27]} scale={[0.59, 0.83, 1.2]} userData={{ name: 'clank_0016:pCube16' }}>
                <mesh geometry={nodes.clank_0016pCube16_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube16_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-129.41, -0.65, -189.49]} rotation={[-Math.PI / 2, Math.PI / 4, -Math.PI / 2]} scale={[0.58, 0.58, 0.63]} userData={{ name: 'clank_0016:pCube26' }}>
                <mesh geometry={nodes.clank_0016pCube26_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCube26_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-129.12, -0.65, -189.9]} rotation={[0, 0, Math.PI / 2]} scale={[0.35, 2.93, 0.35]} userData={{ name: 'clank_0016:pCylinder16' }}>
                <mesh geometry={nodes.clank_0016pCylinder16_clank_0016blinn2_0.geometry} material={materials.clank_0016blinn2} userData={{ name: 'clank_0016:pCylinder16_clank_0016:blinn2_0' }} />
              </group>
              <group position={[-129.39, -0.65, -189.86]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.59, 0.47, 0.59]} userData={{ name: 'clank_0016:pCylinder5' }}>
                <mesh geometry={nodes.clank_0016pCylinder5_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder5_clank_0016:blinn1_0' }} />
              </group>
              <group position={[-131.91, -0.65, -189.93]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1.1, 0.49, 1.1]} userData={{ name: 'clank_0016:pCylinder2' }}>
                <mesh geometry={nodes.clank_0016pCylinder2_clank_0016blinn1_0.geometry} material={materials.clank_0016blinn1} userData={{ name: 'clank_0016:pCylinder2_clank_0016:blinn1_0' }} />
              </group>
            </group>
            <group position={[-9.15, 6.31, 15.97]} rotation={[0, 0, -0.17]} scale={0.06} userData={{ name: 'group2' }}>
              <group position={[-7.73, 69.39, -1005.18]} scale={[3.61, 0.6, 3.61]} userData={{ name: 'pCylinder7' }}>
                <mesh geometry={nodes.pCylinder7_lambert31_0.geometry} material={materials.lambert31} userData={{ name: 'pCylinder7_lambert31_0' }} />
              </group>
              <group position={[0, 67.6, -998.17]} scale={[25.99, 2.66, 25.99]} userData={{ name: 'pCube27' }}>
                <mesh geometry={nodes.pCube27_lambert34_0.geometry} material={materials.lambert9} userData={{ name: 'pCube27_lambert34_0' }} />
              </group>
              <group position={[-5.76, 86.88, -993.34]} scale={5} userData={{ name: 'pSphere1' }}>
                <mesh geometry={nodes.pSphere1_lambert31_0.geometry} material={materials.lambert31} userData={{ name: 'pSphere1_lambert31_0' }} />
              </group>
              <group position={[3.02, 69.39, -1001.79]} scale={[3.61, 0.6, 3.61]} userData={{ name: 'pCylinder8' }}>
                <mesh geometry={nodes.pCylinder8_lambert32_0.geometry} material={materials.lambert31} userData={{ name: 'pCylinder8_lambert32_0' }} />
              </group>
              <group position={[-5.75, 69.39, -993.3]} scale={[5.34, 0.88, 5.34]} userData={{ name: 'pCylinder10' }}>
                <mesh geometry={nodes.pCylinder10_lambert35_0.geometry} material={materials.lambert35} userData={{ name: 'pCylinder10_lambert35_0' }} />
              </group>
              <group position={[7.26, 69.39, -991.6]} scale={[3.61, 0.6, 3.61]} userData={{ name: 'pCylinder9' }}>
                <mesh geometry={nodes.pCylinder9_lambert33_0.geometry} material={materials.lambert31} userData={{ name: 'pCylinder9_lambert33_0' }} />
              </group>
            </group>
            <group position={[-9.15, 6.31, 19.63]} rotation={[0, 0, -0.17]} scale={0.06} userData={{ name: 'group3' }}>
              <group position={[-7.73, 69.39, -1005.18]} scale={[3.61, 0.6, 3.61]} userData={{ name: 'pCylinder7' }}>
                <mesh geometry={nodes.pCylinder7_lambert31_0_1.geometry} material={materials.lambert31} userData={{ name: 'pCylinder7_lambert31_0' }} />
              </group>
              <group position={[0, 67.6, -998.17]} scale={[25.99, 2.66, 25.99]} userData={{ name: 'pCube27' }}>
                <mesh geometry={nodes.pCube27_lambert34_0_1.geometry} material={materials.lambert9} userData={{ name: 'pCube27_lambert34_0' }} />
              </group>
              <group position={[-5.76, 86.88, -993.34]} scale={5} userData={{ name: 'pSphere1' }}>
                <mesh geometry={nodes.pSphere1_lambert31_0_1.geometry} material={materials.lambert31} userData={{ name: 'pSphere1_lambert31_0' }} />
              </group>
              <group position={[3.02, 69.39, -1001.79]} scale={[3.61, 0.6, 3.61]} userData={{ name: 'pCylinder8' }}>
                <mesh geometry={nodes.pCylinder8_lambert32_0_1.geometry} material={materials.lambert31} userData={{ name: 'pCylinder8_lambert32_0' }} />
              </group>
              <group position={[-5.75, 69.39, -993.3]} scale={[5.34, 0.88, 5.34]} userData={{ name: 'pCylinder10' }}>
                <mesh geometry={nodes.pCylinder10_lambert35_0_1.geometry} material={materials.lambert35} userData={{ name: 'pCylinder10_lambert35_0' }} />
              </group>
              <group position={[7.26, 69.39, -991.6]} scale={[3.61, 0.6, 3.61]} userData={{ name: 'pCylinder9' }}>
                <mesh geometry={nodes.pCylinder9_lambert33_0_1.geometry} material={materials.lambert31} userData={{ name: 'pCylinder9_lambert33_0' }} />
              </group>
            </group>
            <group position={[-15.4, 20.39, -50.58]} scale={[2.6, 3.58, 0.7]} userData={{ name: 'pCube28' }}>
              <mesh geometry={nodes.pCube28_blinn8_0.geometry} material={materials.blinn8} userData={{ name: 'pCube28_blinn8_0' }} />
            </group>
            <group position={[-15.4, 19.89, -51.22]} scale={[1.86, 2.56, 0.5]} userData={{ name: 'pCube29' }}>
              <mesh geometry={nodes.pCube29_blinn8_0.geometry} material={materials.blinn8} userData={{ name: 'pCube29_blinn8_0' }} />
            </group>
            <group position={[-15.4, 19.89, -51.78]} scale={[1.86, 2.56, 0.5]} userData={{ name: 'pCube30' }}>
              <mesh geometry={nodes.pCube30_blinn6_0.geometry} material={materials.blinn8} userData={{ name: 'pCube30_blinn6_0' }} />
            </group>
            <group position={[-15.4, 20.39, -52.48]} scale={[2.6, 3.58, 0.7]} userData={{ name: 'pCube31' }}>
              <mesh geometry={nodes.pCube31_blinn7_0.geometry} material={materials.blinn8} userData={{ name: 'pCube31_blinn7_0' }} />
            </group>
            <group position={[-15.4, 20.39, -53.18]} scale={[2.6, 3.58, 0.54]} userData={{ name: 'pCube32' }}>
              <mesh geometry={nodes.pCube32_blinn6_0.geometry} material={materials.blinn8} userData={{ name: 'pCube32_blinn6_0' }} />
            </group>
            <group position={[-15.4, 20.03, -53.86]} scale={[2.6, 2.86, 0.54]} userData={{ name: 'pCube33' }}>
              <mesh geometry={nodes.pCube33_blinn7_0.geometry} material={materials.blinn8} userData={{ name: 'pCube33_blinn7_0' }} />
            </group>
            <group position={[-15.4, 19.89, -54.43]} scale={[1.86, 2.56, 0.5]} userData={{ name: 'pCube34' }}>
              <mesh geometry={nodes.pCube34_blinn7_0.geometry} material={materials.blinn8} userData={{ name: 'pCube34_blinn7_0' }} />
            </group>
            <group position={[-1.3, 9.93, -58.49]} scale={[0.58, 0.64, 0.12]} userData={{ name: 'pCube35' }}>
              <mesh geometry={nodes.pCube35_blinn6_0.geometry} material={materials.blinn8} userData={{ name: 'pCube35_blinn6_0' }} />
            </group>
            <group position={[-9.23, 10.2, -58.01]} rotation={[0, 0.79, 0]} scale={[0.58, 0.64, 0.12]} userData={{ name: 'pCube36' }}>
              <mesh geometry={nodes.pCube36_blinn6_0.geometry} material={materials.blinn8} userData={{ name: 'pCube36_blinn6_0' }} />
            </group>
            <group position={[-8.48, 10.2, -58.77]} rotation={[0, 0.79, 0]} scale={[0.58, 0.64, 0.12]} userData={{ name: 'pCube37' }}>
              <mesh geometry={nodes.pCube37_blinn6_0.geometry} material={materials.blinn8} userData={{ name: 'pCube37_blinn6_0' }} />
            </group>
            <group position={[18.6, 13.67, -63.26]} rotation={[-Math.PI, 0, 0]} scale={[0.5, 13.91, 0.5]} userData={{ name: 'pCylinder11' }}>
              <mesh geometry={nodes.pCylinder11_blinn9_0.geometry} material={materials.blinn1} userData={{ name: 'pCylinder11_blinn9_0' }} />
            </group>
            <group position={[20.34, 13.67, -63.26]} rotation={[-Math.PI, 0, 0]} scale={[0.5, 13.91, 0.5]} userData={{ name: 'pCylinder12' }}>
              <mesh geometry={nodes.pCylinder12_blinn9_0.geometry} material={materials.blinn1} userData={{ name: 'pCylinder12_blinn9_0' }} />
            </group>
            <group position={[0.46, 9.5, -56.55]} rotation={[0, 0.49, 0]} scale={[2.31, 0.08, 1.51]} userData={{ name: 'pCube38' }}>
              <mesh geometry={nodes.pCube38_lambert36_0.geometry} material={materials.lambert36} userData={{ name: 'pCube38_lambert36_0' }} />
            </group>
            <group position={[6.53, 8.76, -64.21]} rotation={[0, -1, 0.29]} scale={0.21} userData={{ name: 'group4' }}>
              <group position={[32.93, -3.52, 10.98]} rotation={[Math.PI / 2, -0.32, Math.PI / 2]} scale={[1.96, 6.41, 3.93]} userData={{ name: 'NMSMultyTool_0010:pCube2' }}>
                <mesh geometry={nodes.NMSMultyTool_0010pCube2_NMSMultyTool_0010phong4_0.geometry} material={materials.NMSMultyTool_0010phong4} userData={{ name: 'NMSMultyTool_0010:pCube2_NMSMultyTool_0010:phong4_0' }} />
                <mesh geometry={nodes.NMSMultyTool_0010pCube2_NMSMultyTool_0010phong1_0.geometry} material={materials.NMSMultyTool_0010phong1} userData={{ name: 'NMSMultyTool_0010:pCube2_NMSMultyTool_0010:phong1_0' }} />
              </group>
              <group position={[32.07, -3.23, 6.54]} rotation={[-Math.PI / 2, -1.25, Math.PI / 2]} scale={[1.92, 2.79, 1.68]} userData={{ name: 'NMSMultyTool_0010:pCylinder2' }}>
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder2_NMSMultyTool_0010phong7_0.geometry} material={materials.NMSMultyTool_0010phong7} userData={{ name: 'NMSMultyTool_0010:pCylinder2_NMSMultyTool_0010:phong7_0' }} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder2_NMSMultyTool_0010phong8_0.geometry} material={materials.NMSMultyTool_0010phong8} userData={{ name: 'NMSMultyTool_0010:pCylinder2_NMSMultyTool_0010:phong8_0' }} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder2_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} userData={{ name: 'NMSMultyTool_0010:pCylinder2_NMSMultyTool_0010:phong2_0' }} />
              </group>
              <group position={[30.8, -2.8, 4.33]} rotation={[0, 0, 1.25]} scale={[3, 3, 7.07]} userData={{ name: 'NMSMultyTool_0010:pSphere1' }}>
                <mesh geometry={nodes.NMSMultyTool_0010pSphere1_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} userData={{ name: 'NMSMultyTool_0010:pSphere1_NMSMultyTool_0010:phong2_0' }} />
                <mesh geometry={nodes.NMSMultyTool_0010pSphere1_NMSMultyTool_0010phong5_0.geometry} material={materials.NMSMultyTool_0010phong5} userData={{ name: 'NMSMultyTool_0010:pSphere1_NMSMultyTool_0010:phong5_0' }} />
                <mesh geometry={nodes.NMSMultyTool_0010pSphere1_NMSMultyTool_0010phong6_0.geometry} material={materials.NMSMultyTool_0010phong6} userData={{ name: 'NMSMultyTool_0010:pSphere1_NMSMultyTool_0010:phong6_0' }} />
              </group>
              <group position={[37.94, -5.2, 8.5]} rotation={[Math.PI, 0, -2.82]} scale={[1.06, 2.41, 1.26]} userData={{ name: 'NMSMultyTool_0010:pCylinder1' }}>
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder1_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} userData={{ name: 'NMSMultyTool_0010:pCylinder1_NMSMultyTool_0010:phong2_0' }} />
              </group>
              <group position={[38.69, -5.45, 6.62]} rotation={[0, 0, 1.25]} scale={[2.45, 4.72, 2.45]} userData={{ name: 'NMSMultyTool_0010:pCube1' }}>
                <mesh geometry={nodes.NMSMultyTool_0010pCube1_NMSMultyTool_0010phong1_0.geometry} material={materials.NMSMultyTool_0010phong1} userData={{ name: 'NMSMultyTool_0010:pCube1_NMSMultyTool_0010:phong1_0' }} />
                <mesh geometry={nodes.NMSMultyTool_0010pCube1_NMSMultyTool_0010phong3_0.geometry} material={materials.NMSMultyTool_0010phong3} userData={{ name: 'NMSMultyTool_0010:pCube1_NMSMultyTool_0010:phong3_0' }} />
              </group>
              <group position={[38.06, -5.24, 4.39]} rotation={[Math.PI / 2, -0.32, Math.PI / 2]} scale={[12.11, 4.62, 3.47]} userData={{ name: 'NMSMultyTool_0010:pCube3' }}>
                <mesh geometry={nodes.NMSMultyTool_0010pCube3_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} userData={{ name: 'NMSMultyTool_0010:pCube3_NMSMultyTool_0010:phong2_0' }} />
              </group>
              <group position={[34.48, -0.44, -0.73]} rotation={[-1.64, -1.25, -0.07]} scale={[0.46, 4.83, 0.46]} userData={{ name: 'NMSMultyTool_0010:pCylinder5' }}>
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder5_NMSMultyTool_0010phong1_0.geometry} material={materials.NMSMultyTool_0010phong1} userData={{ name: 'NMSMultyTool_0010:pCylinder5_NMSMultyTool_0010:phong1_0' }} />
              </group>
              <group position={[32.65, -3.42, 4.57]} rotation={[Math.PI / 2, -0.32, Math.PI / 2]} scale={[6.61, 3.91, 2.79]} userData={{ name: 'NMSMultyTool_0010:pSphere3' }}>
                <mesh geometry={nodes.NMSMultyTool_0010pSphere3_NMSMultyTool_0010phong1_0.geometry} material={materials.NMSMultyTool_0010phong1} userData={{ name: 'NMSMultyTool_0010:pSphere3_NMSMultyTool_0010:phong1_0' }} />
              </group>
              <group position={[33.33, -3.79, -0.26]} rotation={[-Math.PI / 2, -1.25, 3.13]} scale={[0.86, 1.52, 0.92]} userData={{ name: 'NMSMultyTool_0010:pCylinder8' }}>
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder8_NMSMultyTool_0010phong7_0.geometry} material={materials.NMSMultyTool_0010phong7} userData={{ name: 'NMSMultyTool_0010:pCylinder8_NMSMultyTool_0010:phong7_0' }} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder8_NMSMultyTool_0010phong8_0.geometry} material={materials.NMSMultyTool_0010phong8} userData={{ name: 'NMSMultyTool_0010:pCylinder8_NMSMultyTool_0010:phong8_0' }} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder8_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} userData={{ name: 'NMSMultyTool_0010:pCylinder8_NMSMultyTool_0010:phong2_0' }} />
              </group>
              <group position={[33.72, -2.43, 3.37]} rotation={[-Math.PI / 2, -1.25, Math.PI / 2]} scale={[0.86, 1.52, 0.92]} userData={{ name: 'NMSMultyTool_0010:pCylinder7' }}>
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder7_NMSMultyTool_0010phong7_0.geometry} material={materials.NMSMultyTool_0010phong7} userData={{ name: 'NMSMultyTool_0010:pCylinder7_NMSMultyTool_0010:phong7_0' }} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder7_NMSMultyTool_0010phong8_0.geometry} material={materials.NMSMultyTool_0010phong8} userData={{ name: 'NMSMultyTool_0010:pCylinder7_NMSMultyTool_0010:phong8_0' }} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder7_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} userData={{ name: 'NMSMultyTool_0010:pCylinder7_NMSMultyTool_0010:phong2_0' }} />
              </group>
              <group position={[34.81, -4.15, 4.33]} rotation={[0, 0, -1.89]} scale={[3, 3, 7.07]} userData={{ name: 'NMSMultyTool_0010:pSphere2' }}>
                <mesh geometry={nodes.NMSMultyTool_0010pSphere2_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} userData={{ name: 'NMSMultyTool_0010:pSphere2_NMSMultyTool_0010:phong2_0' }} />
              </group>
              <group position={[31.31, -2.97, 10.35]} rotation={[-Math.PI / 2, -1.25, 0]} scale={[1.69, 2.46, 1.4]} userData={{ name: 'NMSMultyTool_0010:pCylinder3' }}>
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder3_NMSMultyTool_0010phong9_0.geometry} material={materials.NMSMultyTool_0010phong8} userData={{ name: 'NMSMultyTool_0010:pCylinder3_NMSMultyTool_0010:phong9_0' }} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder3_NMSMultyTool_0010phong1_0.geometry} material={materials.NMSMultyTool_0010phong1} userData={{ name: 'NMSMultyTool_0010:pCylinder3_NMSMultyTool_0010:phong1_0' }} />
              </group>
              <group position={[34.59, -4.08, 10.45]} rotation={[-Math.PI / 2, -1.25, 0]} scale={[1.05, 1.53, 0.95]} userData={{ name: 'NMSMultyTool_0010:pCylinder4' }}>
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder4_NMSMultyTool_0010phong10_0.geometry} material={materials.NMSMultyTool_0010phong8} userData={{ name: 'NMSMultyTool_0010:pCylinder4_NMSMultyTool_0010:phong10_0' }} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder4_NMSMultyTool_0010phong1_0.geometry} material={materials.NMSMultyTool_0010phong1} userData={{ name: 'NMSMultyTool_0010:pCylinder4_NMSMultyTool_0010:phong1_0' }} />
              </group>
            </group>
            <group position={[-10.35, 16.89, -41.87]} rotation={[0, 0, 0.31]} scale={[1, 0.36, 1]} userData={{ name: 'areaLight1' }}>
              <group rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'Object_341' }} />
            </group>
            <group position={[-10.35, 16.89, -33.09]} rotation={[0, 0, 0.31]} scale={[1, 0.36, 1]} userData={{ name: 'areaLight2' }}>
              <group rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'Object_344' }} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hacker80-transformed.glb')
