/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Bscott5 (https://sketchfab.com/Bscott5)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mario-kart-item-box-8f6a2b6b17b844c5b5dfa38375289975
title: Mario Kart Item Box
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    crate_texture: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/mystery-transformed.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Sketchfab_model' }}>
        <group userData={{ name: 'cd3b4644176d4edca8f8af030edb9ab5.obj.cleaner.materialmerger.gles' }}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.crate_texture} userData={{ name: 'Object_2' }} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mystery-transformed.glb')
