/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: moyicat (https://sketchfab.com/moyicat)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/room-14-blender-6ba9fd270bb04ddbb5d8eae11ed58f9f
title: Room 14 / Blender
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cutting_Board_0: THREE.Mesh
    Bread_0: THREE.Mesh
    Cylinder_0: THREE.Mesh
    Cylinder004_0: THREE.Mesh
    Cylinder003_0: THREE.Mesh
    Cylinder001_0: THREE.Mesh
    Cooking_Pot_0: THREE.Mesh
    Cylinder005_0: THREE.Mesh
    Cylinder002_0: THREE.Mesh
    Icosphere021_0: THREE.Mesh
    Icosphere020_0: THREE.Mesh
    Icosphere019_0: THREE.Mesh
    Icosphere018_0: THREE.Mesh
    Icosphere017_0: THREE.Mesh
    Icosphere016_0: THREE.Mesh
    Icosphere015_0: THREE.Mesh
    Bowl_0: THREE.Mesh
    Plate_0: THREE.Mesh
    Cube002_0: THREE.Mesh
    Cube_0: THREE.Mesh
    Cube001_0: THREE.Mesh
    Cube003_0: THREE.Mesh
    Cube004_0: THREE.Mesh
    Bottle_0: THREE.Mesh
    Bottle_1: THREE.Mesh
    Glass_02_0: THREE.Mesh
    Glass_01_0: THREE.Mesh
    Little_Chair_02_0: THREE.Mesh
    Little_Chair_01_0: THREE.Mesh
    Grass_0: THREE.Mesh
    Grass_0_1: THREE.Mesh
    Ball_02_0: THREE.Mesh
    Ball_01_0: THREE.Mesh
    Icosphere014_0: THREE.Mesh
    Icosphere013_0: THREE.Mesh
    Icosphere012_0: THREE.Mesh
    Icosphere011_0: THREE.Mesh
    Icosphere010_0: THREE.Mesh
    Icosphere009_0: THREE.Mesh
    Icosphere008_0: THREE.Mesh
    Icosphere007_0: THREE.Mesh
    Icosphere006_0: THREE.Mesh
    Icosphere005_0: THREE.Mesh
    Icosphere004_0: THREE.Mesh
    Icosphere003_0: THREE.Mesh
    Icosphere002_0: THREE.Mesh
    Icosphere001_0: THREE.Mesh
    Icosphere_0: THREE.Mesh
    Tree_Trunk_0: THREE.Mesh
    SmallRoom_0: THREE.Mesh
    SmallRoom_1: THREE.Mesh
    Bench_White_0: THREE.Mesh
    Flower008_0: THREE.Mesh
    Flower008_1: THREE.Mesh
    Flower008_2: THREE.Mesh
    Flower007_2: THREE.Mesh
    Flower007_0: THREE.Mesh
    Flower007_1: THREE.Mesh
    Flower006_2: THREE.Mesh
    Flower006_0: THREE.Mesh
    Flower006_1: THREE.Mesh
    Flower005_0: THREE.Mesh
    Flower005_1: THREE.Mesh
    Flower005_2: THREE.Mesh
    Flower004_2: THREE.Mesh
    Flower004_0: THREE.Mesh
    Flower004_1: THREE.Mesh
    Flower003_2: THREE.Mesh
    Flower003_0: THREE.Mesh
    Flower003_1: THREE.Mesh
    Flower002_0: THREE.Mesh
    Flower002_1: THREE.Mesh
    Flower002_2: THREE.Mesh
    Flower001_0: THREE.Mesh
    Flower001_1: THREE.Mesh
    Flower001_2: THREE.Mesh
    Flower_0: THREE.Mesh
    Flower_1: THREE.Mesh
    Flower_2: THREE.Mesh
    Pot_0: THREE.Mesh
    Pot_1: THREE.Mesh
    Cube_Seat_01_0: THREE.Mesh
    Cube_Seat_02_0: THREE.Mesh
    Bench_Struct_0: THREE.Mesh
    Bench_Wood_0: THREE.Mesh
    Table_Cloth_0: THREE.Mesh
    Table_Struct_0: THREE.Mesh
    Table_Wood_0: THREE.Mesh
    Wood_Wall_Right_0: THREE.Mesh
    Wood_Wall_Left_0: THREE.Mesh
    Wood_Floor_0: THREE.Mesh
    WallLeft_0: THREE.Mesh
    WallRight_0: THREE.Mesh
    Soil_0: THREE.Mesh
  }
  materials: {
    Bread_Board: THREE.MeshStandardMaterial
    Bread: THREE.MeshStandardMaterial
    Cylinder_0: THREE.MeshStandardMaterial
    Yellow_Pot: THREE.MeshStandardMaterial
    Tomatos: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    Wood_Plate: THREE.MeshStandardMaterial
    Burger_Red: THREE.MeshStandardMaterial
    Burger_Yellow: THREE.MeshStandardMaterial
    Blue_Glass: THREE.MeshStandardMaterial
    Bottle_Label: THREE.MeshStandardMaterial
    Tree_Trunk: THREE.MeshStandardMaterial
    Grass: THREE.MeshStandardMaterial
    Blue_Ball: THREE.MeshStandardMaterial
    ['Flower_Stem.001']: THREE.MeshStandardMaterial
    Little_Room_White: THREE.MeshStandardMaterial
    Little_Room_Dark: THREE.MeshStandardMaterial
    Wood_Bench: THREE.MeshStandardMaterial
    Flower_Paddle: THREE.MeshStandardMaterial
    Flower_Stem: THREE.MeshStandardMaterial
    Flower_Middle: THREE.MeshStandardMaterial
    Flower_Pot: THREE.MeshStandardMaterial
    Light_Soil: THREE.MeshStandardMaterial
    Wood_Table: THREE.MeshStandardMaterial
    Cloth: THREE.MeshStandardMaterial
    Wood_Wall: THREE.MeshStandardMaterial
    Wood_Floor: THREE.MeshStandardMaterial
    Blue_Wall_Light: THREE.MeshStandardMaterial
    Blue_Wall_Dark: THREE.MeshStandardMaterial
    Soil: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/room14.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.6} userData={{ name: 'Sketchfab_model' }}>
        <group userData={{ name: 'Root' }}>
          <group userData={{ name: 'Objects' }}>
            <group position={[2.82, 1.39, 1.51]} rotation={[0, 0, 0.29]} scale={0.36} userData={{ name: 'Bread Set' }}>
              <group userData={{ name: 'Cutting Board' }}>
                <mesh geometry={nodes.Cutting_Board_0.geometry} material={materials.Bread_Board} userData={{ name: 'Cutting Board_0' }} />
              </group>
              <group position={[0, 0, 0.18]} rotation={[0, 0, Math.PI / 4]} scale={[0.5, 1, 1]} userData={{ name: 'Bread' }}>
                <mesh geometry={nodes.Bread_0.geometry} material={materials.Bread} userData={{ name: 'Bread_0' }} />
              </group>
            </group>
            <group position={[1.51, 1.46, 1.51]} rotation={[0, 0, -0.79]} scale={0.2} userData={{ name: 'Plates Stack' }}>
              <group position={[0, 0, 0.05]} scale={[1, 1.2, 1]} userData={{ name: 'Cylinder' }}>
                <mesh geometry={nodes.Cylinder_0.geometry} material={materials.Cylinder_0} userData={{ name: 'Cylinder_0' }} />
              </group>
              <group position={[0, 0, 0.43]} scale={[1, 1.2, 1]} userData={{ name: 'Cylinder.004' }}>
                <mesh geometry={nodes.Cylinder004_0.geometry} material={materials.Cylinder_0} userData={{ name: 'Cylinder.004_0' }} />
              </group>
              <group position={[0, 0, 0.33]} scale={[1, 1.2, 1]} userData={{ name: 'Cylinder.003' }}>
                <mesh geometry={nodes.Cylinder003_0.geometry} material={materials.Cylinder_0} userData={{ name: 'Cylinder.003_0' }} />
              </group>
              <group position={[0, 0, 0.14]} scale={[1, 1.2, 1]} userData={{ name: 'Cylinder.001' }}>
                <mesh geometry={nodes.Cylinder001_0.geometry} material={materials.Cylinder_0} userData={{ name: 'Cylinder.001_0' }} />
              </group>
              <group position={[0, 0, 0.58]} scale={[0.8, 0.96, 0.83]} userData={{ name: 'Cooking Pot' }}>
                <mesh geometry={nodes.Cooking_Pot_0.geometry} material={materials.Yellow_Pot} userData={{ name: 'Cooking Pot_0' }} />
              </group>
              <group position={[0, 0, 0.52]} scale={[1, 1.2, 1]} userData={{ name: 'Cylinder.005' }}>
                <mesh geometry={nodes.Cylinder005_0.geometry} material={materials.Cylinder_0} userData={{ name: 'Cylinder.005_0' }} />
              </group>
              <group position={[0, 0, 0.24]} scale={[1, 1.2, 1]} userData={{ name: 'Cylinder.002' }}>
                <mesh geometry={nodes.Cylinder002_0.geometry} material={materials.Cylinder_0} userData={{ name: 'Cylinder.002_0' }} />
              </group>
            </group>
            <group position={[2.06, 0.64, 1.51]} scale={0.3} userData={{ name: 'Bowl of Tomatos' }}>
              <group position={[-0.39, -0.02, 1.26]} rotation={[-0.28, 0.05, 0.51]} userData={{ name: 'Icosphere.021' }}>
                <mesh geometry={nodes.Icosphere021_0.geometry} material={materials.Tomatos} userData={{ name: 'Icosphere.021_0' }} />
              </group>
              <group position={[-0.34, -0.52, 0.78]} rotation={[0, 0, 0.76]} userData={{ name: 'Icosphere.020' }}>
                <mesh geometry={nodes.Icosphere020_0.geometry} material={materials.Tomatos} userData={{ name: 'Icosphere.020_0' }} />
              </group>
              <group position={[0.44, -0.24, 0.81]} rotation={[0, 0, 0.76]} userData={{ name: 'Icosphere.019' }}>
                <mesh geometry={nodes.Icosphere019_0.geometry} material={materials.Tomatos} userData={{ name: 'Icosphere.019_0' }} />
              </group>
              <group position={[0.11, 0.56, 0.64]} rotation={[0, 0, 0.17]} userData={{ name: 'Icosphere.018' }}>
                <mesh geometry={nodes.Icosphere018_0.geometry} material={materials.Tomatos} userData={{ name: 'Icosphere.018_0' }} />
              </group>
              <group position={[0.51, 0.16, 0.03]} rotation={[0, 0, -0.45]} userData={{ name: 'Icosphere.017' }}>
                <mesh geometry={nodes.Icosphere017_0.geometry} material={materials.Tomatos} userData={{ name: 'Icosphere.017_0' }} />
              </group>
              <group position={[0.11, -0.58, 0.18]} userData={{ name: 'Icosphere.016' }}>
                <mesh geometry={nodes.Icosphere016_0.geometry} material={materials.Tomatos} userData={{ name: 'Icosphere.016_0' }} />
              </group>
              <group position={[-0.34, 0.23, 0.03]} rotation={[0, 0, -0.45]} userData={{ name: 'Icosphere.015' }}>
                <mesh geometry={nodes.Icosphere015_0.geometry} material={materials.Tomatos} userData={{ name: 'Icosphere.015_0' }} />
              </group>
              <group userData={{ name: 'Bowl' }}>
                <mesh geometry={nodes.Bowl_0.geometry} material={materials.Glass} userData={{ name: 'Bowl_0' }} />
              </group>
            </group>
            <group position={[0.37, 1.09, 1.5]} rotation={[0, 0, 2.73]} scale={0.3} userData={{ name: 'Plate Combo' }}>
              <group userData={{ name: 'Plate' }}>
                <mesh geometry={nodes.Plate_0.geometry} material={materials.Wood_Plate} userData={{ name: 'Plate_0' }} />
              </group>
              <group userData={{ name: 'Burger' }}>
                <group position={[-0.67, -0.97, 0.32]} rotation={[0, 0, -0.25]} scale={0.45} userData={{ name: 'Cube.002' }}>
                  <mesh geometry={nodes.Cube002_0.geometry} material={materials.Burger_Red} userData={{ name: 'Cube.002_0' }} />
                </group>
                <group position={[-0.65, -0.97, 0.1]} rotation={[0, 0, -0.23]} scale={0.45} userData={{ name: 'Cube' }}>
                  <mesh geometry={nodes.Cube_0.geometry} material={materials.Burger_Yellow} userData={{ name: 'Cube_0' }} />
                </group>
                <group position={[-0.65, -1.02, 0.24]} rotation={[0, 0, -0.15]} scale={0.45} userData={{ name: 'Cube.001' }}>
                  <mesh geometry={nodes.Cube001_0.geometry} material={materials.Burger_Red} userData={{ name: 'Cube.001_0' }} />
                </group>
                <group position={[-0.65, -0.97, 0.39]} rotation={[0, 0, 0.11]} scale={0.45} userData={{ name: 'Cube.003' }}>
                  <mesh geometry={nodes.Cube003_0.geometry} material={materials.Burger_Red} userData={{ name: 'Cube.003_0' }} />
                </group>
                <group position={[-0.65, -0.97, 0.47]} rotation={[0, 0, -0.23]} scale={0.45} userData={{ name: 'Cube.004' }}>
                  <mesh geometry={nodes.Cube004_0.geometry} material={materials.Burger_Yellow} userData={{ name: 'Cube.004_0' }} />
                </group>
              </group>
              <group position={[0.24, -0.29, 0.1]} scale={0.7} userData={{ name: 'Bottle' }}>
                <mesh geometry={nodes.Bottle_0.geometry} material={materials.Blue_Glass} userData={{ name: 'Bottle_0' }} />
                <mesh geometry={nodes.Bottle_1.geometry} material={materials.Bottle_Label} userData={{ name: 'Bottle_1' }} />
              </group>
              <group position={[1.18, 0.21, 0.1]} scale={0.64} userData={{ name: 'Glass 02' }}>
                <mesh geometry={nodes.Glass_02_0.geometry} material={materials.Glass} userData={{ name: 'Glass 02_0' }} />
              </group>
              <group position={[0.41, 0.93, 0.1]} scale={0.79} userData={{ name: 'Glass 01' }}>
                <mesh geometry={nodes.Glass_01_0.geometry} material={materials.Glass} userData={{ name: 'Glass 01_0' }} />
              </group>
            </group>
            <group userData={{ name: 'On the Grass' }}>
              <group position={[2.29, -3.42, 0]} rotation={[0, 0, 1.14]} scale={0.6} userData={{ name: 'Little Chair 02' }}>
                <mesh geometry={nodes.Little_Chair_02_0.geometry} material={materials.Tree_Trunk} userData={{ name: 'Little Chair 02_0' }} />
              </group>
              <group position={[3.54, -3.27, 0]} rotation={[0, 0, 2.75]} scale={0.6} userData={{ name: 'Little Chair 01' }}>
                <mesh geometry={nodes.Little_Chair_01_0.geometry} material={materials.Tree_Trunk} userData={{ name: 'Little Chair 01_0' }} />
              </group>
              <group position={[3, -3, 0.08]} rotation={[0.24, -0.08, -1.65]} scale={[0.18, 0.18, 0.24]} userData={{ name: 'Grass' }}>
                <mesh geometry={nodes.Grass_0.geometry} material={materials.Grass} userData={{ name: 'Grass_0' }} />
                <mesh geometry={nodes.Grass_0_1.geometry} material={materials.Grass} userData={{ name: 'Grass_0' }} />
              </group>
              <group position={[2.06, -2.61, 0]} scale={0.12} userData={{ name: 'Ball 02' }}>
                <mesh geometry={nodes.Ball_02_0.geometry} material={materials.Blue_Ball} userData={{ name: 'Ball 02_0' }} />
              </group>
              <group position={[1.66, -3.08, 0]} scale={0.12} userData={{ name: 'Ball 01' }}>
                <mesh geometry={nodes.Ball_01_0.geometry} material={materials.Blue_Ball} userData={{ name: 'Ball 01_0' }} />
              </group>
              <group position={[1, -3.6, 0]} userData={{ name: 'Tree' }}>
                <group position={[-0.64, -0.21, 6.97]} rotation={[0.28, -0.86, -0.84]} scale={[0.6, 0.4, 0.94]} userData={{ name: 'Icosphere.014' }}>
                  <mesh geometry={nodes.Icosphere014_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.014_0' }} />
                </group>
                <group position={[-1.17, 0.19, 4.83]} rotation={[-0.11, -1.01, 1.97]} scale={[0.61, 0.25, 1.36]} userData={{ name: 'Icosphere.013' }}>
                  <mesh geometry={nodes.Icosphere013_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.013_0' }} />
                </group>
                <group position={[1.6, -0.71, 6.23]} rotation={[0.55, 0.52, 0.62]} scale={[0.44, 0.3, 1.22]} userData={{ name: 'Icosphere.012' }}>
                  <mesh geometry={nodes.Icosphere012_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.012_0' }} />
                </group>
                <group position={[0.55, -0.34, 5.06]} rotation={[0.24, 0.35, 0.68]} scale={[0.82, 0.59, 1.2]} userData={{ name: 'Icosphere.011' }}>
                  <mesh geometry={nodes.Icosphere011_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.011_0' }} />
                </group>
                <group position={[2.02, 0.05, 6.08]} rotation={[0.19, 0.54, 0.73]} scale={[0.74, 0.4, 1.21]} userData={{ name: 'Icosphere.010' }}>
                  <mesh geometry={nodes.Icosphere010_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.010_0' }} />
                </group>
                <group position={[1.19, 0.32, 4.44]} rotation={[-0.25, 0.67, 1.36]} scale={[0.87, 0.47, 1.42]} userData={{ name: 'Icosphere.009' }}>
                  <mesh geometry={nodes.Icosphere009_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.009_0' }} />
                </group>
                <group position={[0, 0.6, 3.83]} rotation={[-0.44, 0.06, 0.52]} scale={[0.87, 0.47, 1.42]} userData={{ name: 'Icosphere.008' }}>
                  <mesh geometry={nodes.Icosphere008_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.008_0' }} />
                </group>
                <group position={[-0.34, -0.27, 9.35]} rotation={[0.08, -0.22, -0.5]} scale={[0.3, 0.28, 1.17]} userData={{ name: 'Icosphere.007' }}>
                  <mesh geometry={nodes.Icosphere007_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.007_0' }} />
                </group>
                <group position={[-0.58, -0.62, 8.57]} rotation={[0.6, -0.61, -0.02]} scale={[0.18, 0.17, 0.7]} userData={{ name: 'Icosphere.006' }}>
                  <mesh geometry={nodes.Icosphere006_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.006_0' }} />
                </group>
                <group position={[-1.19, 1.02, 4.24]} rotation={[-0.34, -0.39, 0.27]} scale={[0.51, 0.34, 1.39]} userData={{ name: 'Icosphere.005' }}>
                  <mesh geometry={nodes.Icosphere005_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.005_0' }} />
                </group>
                <group position={[2.55, 0.91, 3.92]} rotation={[0.06, 1.07, 2.17]} scale={[0.42, 0.17, 0.93]} userData={{ name: 'Icosphere.004' }}>
                  <mesh geometry={nodes.Icosphere004_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.004_0' }} />
                </group>
                <group position={[-0.08, -1, 5.86]} rotation={[0.59, -0.04, -2.68]} scale={[0.81, 0.33, 1.8]} userData={{ name: 'Icosphere.003' }}>
                  <mesh geometry={nodes.Icosphere003_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.003_0' }} />
                </group>
                <group position={[2.02, 1.95, 5]} rotation={[-0.66, 0.46, -3.03]} scale={[0.71, 0.29, 1.58]} userData={{ name: 'Icosphere.002' }}>
                  <mesh geometry={nodes.Icosphere002_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.002_0' }} />
                </group>
                <group position={[1.37, -0.93, 7.55]} rotation={[0.51, 0.68, 0.65]} scale={[0.51, 0.34, 1.39]} userData={{ name: 'Icosphere.001' }}>
                  <mesh geometry={nodes.Icosphere001_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere.001_0' }} />
                </group>
                <group position={[0.51, -0.27, 8.85]} rotation={[0.21, 0.18, 0.2]} scale={[0.36, 0.33, 1.39]} userData={{ name: 'Icosphere' }}>
                  <mesh geometry={nodes.Icosphere_0.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Icosphere_0' }} />
                </group>
                <group position={[0, 0.01, 0]} scale={[0.8, 0.8, 1]} userData={{ name: 'Tree Trunk' }}>
                  <mesh geometry={nodes.Tree_Trunk_0.geometry} material={materials.Tree_Trunk} userData={{ name: 'Tree Trunk_0' }} />
                </group>
              </group>
              <group position={[-3, -3, 1]} userData={{ name: 'SmallRoom' }}>
                <mesh geometry={nodes.SmallRoom_0.geometry} material={materials.Little_Room_White} userData={{ name: 'SmallRoom_0' }} />
                <mesh geometry={nodes.SmallRoom_1.geometry} material={materials.Little_Room_Dark} userData={{ name: 'SmallRoom_1' }} />
              </group>
            </group>
            <group position={[-3.3, 2, 0]} rotation={[0, 0, -Math.PI / 2]} scale={0.5} userData={{ name: 'Bench White' }}>
              <mesh geometry={nodes.Bench_White_0.geometry} material={materials.Wood_Bench} userData={{ name: 'Bench White_0' }} />
            </group>
            <group position={[-3, -1, 0.06]} userData={{ name: 'Flower Pot' }}>
              <group position={[0.16, -0.04, 0.71]} rotation={[1.03, 0.18, 0.2]} scale={0.12} userData={{ name: 'Flower.008' }}>
                <mesh geometry={nodes.Flower008_0.geometry} material={materials.Flower_Paddle} userData={{ name: 'Flower.008_0' }} />
                <mesh geometry={nodes.Flower008_1.geometry} material={materials.Flower_Stem} userData={{ name: 'Flower.008_1' }} />
                <mesh geometry={nodes.Flower008_2.geometry} material={materials.Flower_Middle} userData={{ name: 'Flower.008_2' }} />
              </group>
              <group position={[-0.02, 0.02, 0.69]} rotation={[0.86, -0.45, -0.21]} scale={0.07} userData={{ name: 'Flower.007' }}>
                <mesh geometry={nodes.Flower007_2.geometry} material={materials.Flower_Middle} userData={{ name: 'Flower.007_2' }} />
                <mesh geometry={nodes.Flower007_0.geometry} material={materials.Flower_Paddle} userData={{ name: 'Flower.007_0' }} />
                <mesh geometry={nodes.Flower007_1.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Flower.007_1' }} />
              </group>
              <group position={[-0.16, -0.08, 0.7]} rotation={[0.98, 0.52, 0.45]} scale={0.07} userData={{ name: 'Flower.006' }}>
                <mesh geometry={nodes.Flower006_2.geometry} material={materials.Flower_Middle} userData={{ name: 'Flower.006_2' }} />
                <mesh geometry={nodes.Flower006_0.geometry} material={materials.Flower_Paddle} userData={{ name: 'Flower.006_0' }} />
                <mesh geometry={nodes.Flower006_1.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Flower.006_1' }} />
              </group>
              <group position={[0.11, 0.25, 0.76]} rotation={[-0.77, -0.47, -2.6]} scale={0.14} userData={{ name: 'Flower.005' }}>
                <mesh geometry={nodes.Flower005_0.geometry} material={materials.Flower_Paddle} userData={{ name: 'Flower.005_0' }} />
                <mesh geometry={nodes.Flower005_1.geometry} material={materials.Flower_Stem} userData={{ name: 'Flower.005_1' }} />
                <mesh geometry={nodes.Flower005_2.geometry} material={materials.Flower_Middle} userData={{ name: 'Flower.005_2' }} />
              </group>
              <group position={[-0.14, 0.26, 0.87]} rotation={[0.7, -0.88, -0.61]} scale={0.07} userData={{ name: 'Flower.004' }}>
                <mesh geometry={nodes.Flower004_2.geometry} material={materials.Flower_Middle} userData={{ name: 'Flower.004_2' }} />
                <mesh geometry={nodes.Flower004_0.geometry} material={materials.Flower_Paddle} userData={{ name: 'Flower.004_0' }} />
                <mesh geometry={nodes.Flower004_1.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Flower.004_1' }} />
              </group>
              <group position={[-0.04, 0.1, 0.86]} rotation={[-0.71, -0.68, -2.36]} scale={0.07} userData={{ name: 'Flower.003' }}>
                <mesh geometry={nodes.Flower003_2.geometry} material={materials.Flower_Middle} userData={{ name: 'Flower.003_2' }} />
                <mesh geometry={nodes.Flower003_0.geometry} material={materials.Flower_Paddle} userData={{ name: 'Flower.003_0' }} />
                <mesh geometry={nodes.Flower003_1.geometry} material={materials['Flower_Stem.001']} userData={{ name: 'Flower.003_1' }} />
              </group>
              <group position={[0.14, -0.14, 0.88]} rotation={[-0.94, -0.05, -2.96]} scale={0.1} userData={{ name: 'Flower.002' }}>
                <mesh geometry={nodes.Flower002_0.geometry} material={materials.Flower_Paddle} userData={{ name: 'Flower.002_0' }} />
                <mesh geometry={nodes.Flower002_1.geometry} material={materials.Flower_Stem} userData={{ name: 'Flower.002_1' }} />
                <mesh geometry={nodes.Flower002_2.geometry} material={materials.Flower_Middle} userData={{ name: 'Flower.002_2' }} />
              </group>
              <group position={[-0.13, -0.09, 0.87]} rotation={[0.22, -0.91, -1.19]} scale={0.11} userData={{ name: 'Flower.001' }}>
                <mesh geometry={nodes.Flower001_0.geometry} material={materials.Flower_Paddle} userData={{ name: 'Flower.001_0' }} />
                <mesh geometry={nodes.Flower001_1.geometry} material={materials.Flower_Stem} userData={{ name: 'Flower.001_1' }} />
                <mesh geometry={nodes.Flower001_2.geometry} material={materials.Flower_Middle} userData={{ name: 'Flower.001_2' }} />
              </group>
              <group position={[0, 0, 0.81]} rotation={[-0.74, 0.44, 2.78]} scale={0.15} userData={{ name: 'Flower' }}>
                <mesh geometry={nodes.Flower_0.geometry} material={materials.Flower_Paddle} userData={{ name: 'Flower_0' }} />
                <mesh geometry={nodes.Flower_1.geometry} material={materials.Flower_Stem} userData={{ name: 'Flower_1' }} />
                <mesh geometry={nodes.Flower_2.geometry} material={materials.Flower_Middle} userData={{ name: 'Flower_2' }} />
              </group>
              <group position={[0, 0, 0.06]} rotation={[0, 0, 0.07]} scale={0.5} userData={{ name: 'Pot' }}>
                <mesh geometry={nodes.Pot_0.geometry} material={materials.Flower_Pot} userData={{ name: 'Pot_0' }} />
                <mesh geometry={nodes.Pot_1.geometry} material={materials.Light_Soil} userData={{ name: 'Pot_1' }} />
              </group>
            </group>
            <group position={[1.22, 0.15, 0.06]} rotation={[0, 0, 0.26]} scale={0.35} userData={{ name: 'Cube Seat 01' }}>
              <mesh geometry={nodes.Cube_Seat_01_0.geometry} material={materials.Wood_Bench} userData={{ name: 'Cube Seat 01_0' }} />
            </group>
            <group position={[-0.78, -0.3, 0.06]} rotation={[0, 0, -0.27]} scale={0.35} userData={{ name: 'Cube Seat 02' }}>
              <mesh geometry={nodes.Cube_Seat_02_0.geometry} material={materials.Wood_Bench} userData={{ name: 'Cube Seat 02_0' }} />
            </group>
            <group position={[2.4, 1, 0]} userData={{ name: 'Set Bench' }}>
              <group position={[-1, 1, 0.06]} userData={{ name: 'Bench Struct' }}>
                <mesh geometry={nodes.Bench_Struct_0.geometry} material={materials.Cylinder_0} userData={{ name: 'Bench Struct_0' }} />
              </group>
              <group position={[-1.51, 0.55, 0.9]} userData={{ name: 'Bench Wood' }}>
                <mesh geometry={nodes.Bench_Wood_0.geometry} material={materials.Wood_Table} userData={{ name: 'Bench Wood_0' }} />
              </group>
            </group>
            <group position={[1.5, 1, 0]} userData={{ name: 'Set Table' }}>
              <group position={[-0.01, 0, 1.54]} scale={[1, 0.6, 1]} userData={{ name: 'Table Cloth' }}>
                <mesh geometry={nodes.Table_Cloth_0.geometry} material={materials.Cloth} userData={{ name: 'Table Cloth_0' }} />
              </group>
              <group position={[0, 0, 0.06]} userData={{ name: 'Table Struct' }}>
                <mesh geometry={nodes.Table_Struct_0.geometry} material={materials.Cylinder_0} userData={{ name: 'Table Struct_0' }} />
              </group>
              <group position={[-0.01, 0, 1.5]} userData={{ name: 'Table Wood' }}>
                <mesh geometry={nodes.Table_Wood_0.geometry} material={materials.Wood_Table} userData={{ name: 'Table Wood_0' }} />
              </group>
            </group>
            <group userData={{ name: 'Walls' }}>
              <group position={[-4.95, 0, 1]} rotation={[0, 0, Math.PI / 2]} userData={{ name: 'Wood Wall Right' }}>
                <mesh geometry={nodes.Wood_Wall_Right_0.geometry} material={materials.Wood_Wall} userData={{ name: 'Wood Wall Right_0' }} />
              </group>
              <group position={[0, -3, 1]} userData={{ name: 'Wood Wall Left' }}>
                <mesh geometry={nodes.Wood_Wall_Left_0.geometry} material={materials.Wood_Wall} userData={{ name: 'Wood Wall Left_0' }} />
              </group>
              <group position={[0, -1, 1]} userData={{ name: 'Wood Floor' }}>
                <mesh geometry={nodes.Wood_Floor_0.geometry} material={materials.Wood_Floor} userData={{ name: 'Wood Floor_0' }} />
              </group>
              <group position={[0, -4, 4]} rotation={[-Math.PI / 2, 0, -Math.PI]} userData={{ name: 'WallLeft' }}>
                <mesh geometry={nodes.WallLeft_0.geometry} material={materials.Blue_Wall_Light} userData={{ name: 'WallLeft_0' }} />
              </group>
              <group position={[-4, 0, 4]} rotation={[Math.PI / 2, Math.PI / 2, 0]} userData={{ name: 'WallRight' }}>
                <mesh geometry={nodes.WallRight_0.geometry} material={materials.Blue_Wall_Dark} userData={{ name: 'WallRight_0' }} />
              </group>
              <group userData={{ name: 'Soil' }}>
                <mesh geometry={nodes.Soil_0.geometry} material={materials.Soil} userData={{ name: 'Soil_0' }} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/room14.glb')
